[HPCSetup]
ProjectName = "CH4" # 

NumCPUs = 8
UseGPU = false

MaxHours = 16.0

[Molecule]
Name = "Methane"
CreateGeometry = true

[Computation]
Method = "QChem"
Theory = "SCF"
SpinFlip = false

Multiplicity = 3
Temperature = 1000.0 #Temeprature is in Kelvin Degrees
TimestepDuration = 10.0 #Timestep Duration is in FemtoSeconds

NumBranches = 0
NumStates = 1
NumTrajectories = 32
NumTimesteps = 2500