[HPCSetup]
ProjectName = "M0L-Test" 

NumCPUs = 8
UseGPU = false

MaxHours = 16.0

[Molecule]
Name = "Molecule"
CreateGeometry = true

[Computation]
Method = "QChem"
Theory = "SCF"
SpinFlip = true

Multiplicity = 3
Temperature = 1000.0 #Temperature is in Kelvin Degrees
TimestepDuration = 10.0 #Timestep Duration is in FemtoSeconds

NumBranches = 0
NumStates = 1
NumTrajectories = 32
NumTimesteps = 2500