[HPCSetup]
RunFolder = "M0L-Test" # Name of the Folder used to Hold Processed Data

NumCPUs = 8
UseGPU = false

MaxHours = 16.0

[Molecule]
Name = "Molecule"

CreateGeometry = true
GeometryStartingIndex = 0 # Used only when CreateGeometry is false

[Computation]
Method = "QChem"

Multiplicity = 3
Temperature = 1000.0 # Temeprature is in Kelvin Degrees
TimestepDuration = 10.0

NumBranches = 0
NumStates = 1
NumTrajectories = 2
NumTimesteps = 2500